apiVersion: apps/v1
kind: Deployment
metadata:
  name: nudity-detect-v1
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nudity-detect-v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nudity-detect-v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node/type
                    operator: In
                    values:
                      - AIGPU
      containers:
        # - command: ["./RotateAngleDetect"]
        - env:
            - name: CURRENT_ENV
              value: LOCAL
            - name: APOLLO_HOST
              value: http://apollo-config:8080
            - name: APOLLO_APPLICATION
              value: nudity-detect
            - name: SERVICE_TYPE
              value: image
            - name: serverName
              value: GODHAND-NUDITYDETECT
            - name: serverHost
              value: nudity-detect-v1
            - name: LD_LIBRARY_PATH
              value: /project/bin/libs/linux/gpu:/project/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
          image: swr.cn-north-4.myhuaweicloud.com/edu-integration-h/nuditydetect_service:huawei-20221111185733
          imagePullPolicy: IfNotPresent
          name: nudity-detect-v1-containers
          ports:
            - containerPort: 8889
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: 0.25
              cpu: "2"
              memory: 4Gi
            requests:
              nvidia.com/gpu: 0.25
              cpu: "1"
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: default-secret
      tolerations:
        - effect: NoSchedule
          key: ai
          operator: Equal
          value: gpu
      volumes:
        - hostPath:
            path: /etc/localtime
          name: host-time
---
apiVersion: v1
kind: Service
metadata:
  name: nudity-detect-v1
  namespace: test
  labels:
    run: nudity-detect-v1
spec:
  ports:
    - port: 8889
      targetPort: 8889
  selector:
    run: nudity-detect-v1