apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: godhand-nudity-detect-v2
  namespace: godhand-godeye-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: godhand-nudity-detect-v2
  template:
    metadata:
      labels:
        run: godhand-nudity-detect-v2
        appName: GODHAND-NUDITYDETECT
    spec:
      affinity:
        #节点亲和性
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node/type
                    operator: In
                    values:
                      - AIGPU2
      tolerations:
        - effect: NoExecute
          key: AI_Common
          operator: Equal
          value: paas
      containers:
        - name: godhand-nudity-detect-v2-containers
          image:
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
          ports:
            - containerPort: 8889
          readinessProbe:
            failureThreshold: 3
            httpGet: { path: /welcome, port: 8889, scheme: HTTP }
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 100
          env:
            - name: CURRENT_ENV
              value: TEST
            - name: serverName
              value: GODHAND-NUDITYDETECT
            - name: serverHost
              value: godhand-nudity-detect-v2
            - name: APOLLO_HOST
              value: http://godhand-apollo-config:8080
            - name: APOLLO_APPLICATION
              value: nudity-detect
            - name: SERVICE_TYPE
              value: image
          resources:
            requests:
              aliyun.com/gpu-mem: '4'
              cpu: 1
              memory: 3000Mi
            limits:
              aliyun.com/gpu-mem: '4'
              cpu: 2
              memory: 4000Mi
      imagePullSecrets:
        - name: godhand-regcred
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: godhand-nudity-detect-v2
  namespace: godhand-godeye-test
  labels:
    run: godhand-nudity-detect-v2
spec:
  type: ClusterIP
  ports:
    - port: 8889
  selector:
    run: godhand-nudity-detect-v2
